/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import CONTROL.ControleAluno;
import MODEL.Aluno;
import MODEL.Curso;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class JfAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form JfAluno
     */
    public JfAluno() {
        initComponents();
        carregarCursosComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JbCarregarCampos = new javax.swing.JButton();
        JbCadastrarAluno = new javax.swing.JButton();
        JbConsultarAluno = new javax.swing.JButton();
        JbEditarAluno = new javax.swing.JButton();
        JbExcluirAluno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAluno = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JftfCPFAluno = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JftfDataNascimentoAluno = new javax.swing.JFormattedTextField();
        JtfNomeAluno = new javax.swing.JTextField();
        JtfMatriculaAluno = new javax.swing.JTextField();
        JtfCodigoAluno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CbxAlunoCurso = new javax.swing.JComboBox<>();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Formulário dos Alunos");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF");

        JbCarregarCampos.setBackground(new java.awt.Color(102, 102, 102));
        JbCarregarCampos.setForeground(new java.awt.Color(255, 255, 255));
        JbCarregarCampos.setText("CARREGAR CAMPOS");
        JbCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarCamposActionPerformed(evt);
            }
        });

        JbCadastrarAluno.setBackground(new java.awt.Color(102, 102, 102));
        JbCadastrarAluno.setForeground(new java.awt.Color(255, 255, 255));
        JbCadastrarAluno.setText("CADASTRAR");
        JbCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarAlunoActionPerformed(evt);
            }
        });

        JbConsultarAluno.setBackground(new java.awt.Color(102, 102, 102));
        JbConsultarAluno.setForeground(new java.awt.Color(255, 255, 255));
        JbConsultarAluno.setText("CONSULTAR");
        JbConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarAlunoActionPerformed(evt);
            }
        });

        JbEditarAluno.setBackground(new java.awt.Color(102, 102, 102));
        JbEditarAluno.setForeground(new java.awt.Color(255, 255, 255));
        JbEditarAluno.setText("EDITAR");
        JbEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEditarAlunoActionPerformed(evt);
            }
        });

        JbExcluirAluno.setBackground(new java.awt.Color(102, 102, 102));
        JbExcluirAluno.setForeground(new java.awt.Color(255, 255, 255));
        JbExcluirAluno.setText("EXCLUIR");
        JbExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirAlunoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matrícula");

        JTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "MATRÍCULA", "NOME DO CURSO", "CPF", "DATA DE NASCIMENTO", "CÓDIGO CURSO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableAluno);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");

        try {
            JftfCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento");

        try {
            JftfDataNascimentoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JtfCodigoAluno.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Curso");

        CbxAlunoCurso.setBackground(new java.awt.Color(40, 40, 40));
        CbxAlunoCurso.setForeground(new java.awt.Color(255, 255, 255));
        CbxAlunoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        CbxAlunoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxAlunoCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(JbConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(JbEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(JbExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(JbCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JftfCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(JtfCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(JtfMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JtfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(JftfDataNascimentoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbxAlunoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(JtfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfCodigoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JftfCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JftfDataNascimentoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CbxAlunoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCadastrarAluno)
                    .addComponent(JbConsultarAluno)
                    .addComponent(JbEditarAluno)
                    .addComponent(JbExcluirAluno)
                    .addComponent(JbCarregarCampos))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarCamposActionPerformed
        // TODO add your handling code here:
        carregarCampos();
    }//GEN-LAST:event_JbCarregarCamposActionPerformed

    private void JbCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        cadastrarAlunoview();
        limparCampos();
    }//GEN-LAST:event_JbCadastrarAlunoActionPerformed

    private void JbConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarAlunoActionPerformed
        // TODO add your handling code here:
        listarAlunoView();
    }//GEN-LAST:event_JbConsultarAlunoActionPerformed

    private void JbEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEditarAlunoActionPerformed
        // TODO add your handling code here:
        alterarAlunoView();
        listarAlunoView();
        limparCampos();
        
    }//GEN-LAST:event_JbEditarAlunoActionPerformed

    private void JbExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirAlunoActionPerformed
        // TODO add your handling code here:
        excluirAlunoView();
        limparCampos();
    }//GEN-LAST:event_JbExcluirAlunoActionPerformed

    private void CbxAlunoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxAlunoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxAlunoCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxAlunoCurso;
    private javax.swing.JTable JTableAluno;
    private javax.swing.JButton JbCadastrarAluno;
    private javax.swing.JButton JbCarregarCampos;
    private javax.swing.JButton JbConsultarAluno;
    private javax.swing.JButton JbEditarAluno;
    private javax.swing.JButton JbExcluirAluno;
    private javax.swing.JFormattedTextField JftfCPFAluno;
    private javax.swing.JFormattedTextField JftfDataNascimentoAluno;
    private javax.swing.JTextField JtfCodigoAluno;
    private javax.swing.JTextField JtfMatriculaAluno;
    private javax.swing.JTextField JtfNomeAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cadastrarAlunoview(){
        if(validarCampos()){
            try {
                Aluno objAluno = new Aluno();
                objAluno.setMatricula_aluno(Integer.parseInt(JtfMatriculaAluno.getText()));
                objAluno.setNome_aluno(JtfNomeAluno.getText());
                objAluno.setCpf_aluno(JftfCPFAluno.getText().replace(".", "").replace("-", ""));
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date dataNasc = sdf.parse(JftfDataNascimentoAluno.getText());
                objAluno.setData_nasc_aluno(dataNasc);
                
                // Buscar p curso selecionado pelo nome
                String nomeCursoSelecionado = CbxAlunoCurso.getSelectedItem().toString();
                if(!nomeCursoSelecionado.equals("SELECIONE")){
                    ControleAluno objControleAluno = new ControleAluno();
                    ArrayList<Curso> listaCursos = objControleAluno.consultarCursosAtivos();
                    
                    //Encontrar o curso pelo nome
                    Curso cursoSelecionado = null;
                    for (Curso curso : listaCursos) {
                        if(curso.getNome_curso().equals(nomeCursoSelecionado)){
                           cursoSelecionado = curso;
                           break;
                        }
                }
                    
                if(cursoSelecionado!= null){
                   objAluno.setCurso(cursoSelecionado);
                   objControleAluno.cadastrarAluno(objAluno);
                    JOptionPane.showMessageDialog(null, "Aluno Cadastrado com Sucesso!!!");
                    //listarAlunoview();
                } else{
                    JOptionPane.showMessageDialog(null, "Curso não encontrado" );
                }
                } else{
                    JOptionPane.showMessageDialog(null, "Selecione um curso válido" );
                }
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar: !" + erro.getMessage() );
            }
        }
    }
    
    private void listarAlunoView(){
    try {
        ControleAluno objcontroAluno = new ControleAluno();
        DefaultTableModel model = (DefaultTableModel) JTableAluno.getModel();
        
        
        model.setRowCount(0);
        
        ArrayList<Aluno> lista = objcontroAluno.consultarAluno();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        for(int num = 0; num < lista.size(); num++){
            String dataFormatada = sdf.format(lista.get(num).getData_nasc_aluno());
            
            model.addRow(new Object[]{
                lista.get(num).getId_aluno(),
                lista.get(num).getMatricula_aluno(),
                lista.get(num).getNome_aluno(),
                lista.get(num).getCpf_aluno(),
                dataFormatada,
                lista.get(num).getCurso().getNome_curso()
            });
        }
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(null, "Erro ao listar alunos: " + erro.getMessage());
    }
}
    
    private void carregarCampos(){
        int linha = JTableAluno.getSelectedRow();
        if (linha != -1) {
            JtfCodigoAluno.setText(JTableAluno.getValueAt(linha, 0).toString());
            JtfMatriculaAluno.setText(JTableAluno.getValueAt(linha, 1).toString());
            JtfNomeAluno.setText(JTableAluno.getValueAt(linha, 2).toString());
            JftfCPFAluno.setText(JTableAluno.getValueAt(linha, 3).toString());
            JftfDataNascimentoAluno.setText(JTableAluno.getValueAt(linha, 4).toString());
            
            // Buscar o cusro correspondente no Combobox - versão simples
            String nomeCurso = JTableAluno.getValueAt(linha, 5).toString();
            CbxAlunoCurso.setSelectedItem(nomeCurso);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno da tabela para carregar os campos");
        }
    }
    
    private void alterarAlunoView(){
        if(JtfCodigoAluno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um aluno para editar");
            return;
        }
        if(validarCampos()){
            try{
                Aluno objAluno = new Aluno();
                objAluno.setId_aluno(Integer.parseInt(JtfCodigoAluno.getText()));
                objAluno.setMatricula_aluno(Integer.parseInt(JtfMatriculaAluno.getText()));
                objAluno.setNome_aluno((JtfNomeAluno.getText()));
                objAluno.setCpf_aluno((JftfCPFAluno.getText()));
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date dataNasc = sdf.parse(JftfDataNascimentoAluno.getText());
                objAluno.setData_nasc_aluno(dataNasc);
                
                String nomeCursoSelecionado = CbxAlunoCurso.getSelectedItem().toString();
                if(!nomeCursoSelecionado.equals("SELECIONE")){
                    ControleAluno objControleAluno = new ControleAluno();
                    ArrayList<Curso> listaCursos  = objControleAluno.consultarCursosAtivos();
                    
                    Curso cursoSelecionado = null;
                    for (Curso curso: listaCursos){
                        if(curso.getNome_curso().equals(nomeCursoSelecionado)) {
                            cursoSelecionado = curso;
                            break;
                            
                        }
                    }
                    if(cursoSelecionado != null){
                    objAluno.setCurso(cursoSelecionado);
                    objControleAluno.alterarAluno(objAluno);
                    JOptionPane.showMessageDialog(null, "Aluno alterado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Curso não encontrado!");

                    }
            } else{
                JOptionPane.showMessageDialog(null, "Selecione um curso válido");
                }
               
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar aluno" + erro);
                
            }
        }
    } 
    private void excluirAlunoView(){
        if (JtfCodigoAluno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um aluno para excluir");
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este aluno?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(confirmar == JOptionPane.YES_OPTION){
        try {
            Aluno objAluno = new Aluno();
            objAluno.setId_aluno(Integer.parseInt(JtfCodigoAluno.getText()));
            
            ControleAluno objControleAluno = new ControleAluno();
            objControleAluno.excluirAluno(objAluno);
            JOptionPane.showMessageDialog(null, "Aluno Excluído com Sucesso");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir aluno" + erro.getMessage());
            }
        }
    }
    
    private void limparCampos(){
        JtfCodigoAluno.setText("");
        JtfMatriculaAluno.setText("");
        JtfNomeAluno.setText("");
        JftfCPFAluno.setText("");
        JftfDataNascimentoAluno.setText("");
        
        if(CbxAlunoCurso.getItemCount() > 0){
            CbxAlunoCurso.setSelectedIndex(0);
        }
        JtfMatriculaAluno.requestFocus();
    }
    
    private boolean validarCampos(){
        if (JtfMatriculaAluno.getText().isEmpty()
            || JtfNomeAluno.getText().isEmpty()
            || JftfCPFAluno.getText().isEmpty()
            || CbxAlunoCurso.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!");
            return false;
        }
        
        // Validar se a matricula e numerica
        try {
            Integer.parseInt(JtfMatriculaAluno.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A matricula deve conter apenas numeros");
            return false;
        }
        
    // Validar se a data está completa "dd/mm/yyyy"
    if (JftfDataNascimentoAluno.getText().contains(" ")){
        JOptionPane.showMessageDialog(null, "Data de nascimento inválida!");
        return false;
    }
    if (JftfCPFAluno.getText().contains(" ")){
    JOptionPane.showMessageDialog(null, "CPF inválido!");
    return false;
        }
    return true;
    }
    
    private void carregarCursosComboBox(){
        try {
            ControleAluno objControleAluno = new ControleAluno();
            ArrayList<Curso> listaCursos = objControleAluno.consultarCursosAtivos();
            
            CbxAlunoCurso.removeAllItems();
            CbxAlunoCurso.addItem("SELECIONE");
            
            for(Curso curso : listaCursos) {
                CbxAlunoCurso.addItem(curso.getNome_curso());
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar cursos" + erro.getMessage());
        }
    }
}