/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JInternalFrame;

/**
 *
 * @author Kaliandrik
 */
public class JfMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfMenu.class.getName());

    /**
     * Creates new form JfMenu
     */
    public JfMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        /**
     * Método para fechar todos os frames abertos no DesktopPane
     */
    private void fecharFramesAbertos() {
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            frame.dispose();
        }
    }

        
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuAluno = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItemCurso = new javax.swing.JMenu();
        jMenucursobruno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMenuItemCurso1 = new javax.swing.JMenu();
        jMenucursobruno1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("ALUNO");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        JMenuAluno.setText("FormAluno");
        JMenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAlunoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuAluno.add(jMenuItem1);

        jMenu1.add(JMenuAluno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CURSO");

        JMenuItemCurso.setText("FormCurso");
        JMenuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCursoActionPerformed(evt);
            }
        });

        jMenucursobruno.setText("Curso");
        jMenucursobruno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucursobrunoActionPerformed(evt);
            }
        });
        JMenuItemCurso.add(jMenucursobruno);

        jMenu2.add(JMenuItemCurso);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("LIVRO");

        JMenuItemCurso1.setText("FormLivro");
        JMenuItemCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCurso1ActionPerformed(evt);
            }
        });

        jMenucursobruno1.setText("Livro");
        jMenucursobruno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucursobruno1ActionPerformed(evt);
            }
        });
        JMenuItemCurso1.add(jMenucursobruno1);

        jMenu4.add(JMenuItemCurso1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAlunoActionPerformed
    fecharFramesAbertos();
    JfAluno telaaluno = new JfAluno();
    jDesktopPane1.add(telaaluno);
    telaaluno.setVisible(true);
    telaaluno.setClosable(true);


    }//GEN-LAST:event_JMenuAlunoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    fecharFramesAbertos();
        JfAluno telaaluno = new JfAluno();
        jDesktopPane1.add(telaaluno);
        telaaluno.setVisible(true);
        telaaluno.setClosable(true);    // Botão de fechar
        telaaluno.setMaximizable(true); // Botão de maximizar
        telaaluno.setIconifiable(true); // Botão de minimizar
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenucursobrunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucursobrunoActionPerformed
    fecharFramesAbertos();
        JifCurso telacurso = new JifCurso();
        jDesktopPane1.add(telacurso);
        
        // --- PARTE CORRIGIDA ---
        telacurso.setVisible(true); // Estava faltando

        // Habilita os botões da janela interna
        telacurso.setClosable(true);    // Botão de fechar
        telacurso.setMaximizable(true); // Botão de maximizar
        telacurso.setIconifiable(true); // Botão de minimizar
    }//GEN-LAST:event_jMenucursobrunoActionPerformed

    private void JMenuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCursoActionPerformed
     JifCurso telacurso = new JifCurso();
     jDesktopPane1.add(telacurso);
     telacurso.setVisible(true);
     telacurso.setClosable(true);    // Botão de fechar
        telacurso.setMaximizable(true); // Botão de maximizar
        telacurso.setIconifiable(true);
    }//GEN-LAST:event_JMenuItemCursoActionPerformed

    private void jMenucursobruno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucursobruno1ActionPerformed
     JifLivros telalivros = new JifLivros();
     jDesktopPane1.add(telalivros);
     telalivros.setVisible(true);
     telalivros.setClosable(true);    // Botão de fechar
        telalivros.setMaximizable(true); // Botão de maximizar
        telalivros.setIconifiable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenucursobruno1ActionPerformed

    private void JMenuItemCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemCurso1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAluno;
    private javax.swing.JMenu JMenuItemCurso;
    private javax.swing.JMenu JMenuItemCurso1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenucursobruno;
    private javax.swing.JMenuItem jMenucursobruno1;
    // End of variables declaration//GEN-END:variables
}
