package View;

import CONTROL.ControleCurso;
import MODEL.Curso;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JifCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifCurso
     */
    public JifCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JbCadastrarCurso = new javax.swing.JButton();
        JbConsultarCurso = new javax.swing.JButton();
        JbEditarCurso = new javax.swing.JButton();
        JbExcluirCurso = new javax.swing.JButton();
        JbCarregarCamposCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JbTabelCurso = new javax.swing.JTable();
        CbxStatusCurso = new javax.swing.JComboBox<>();
        JtfCodigoCurso = new javax.swing.JTextField();
        JtfNomeCurso = new javax.swing.JTextField();

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("EXCLUIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Formulário dos Cursos");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Curso");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código");

        JbCadastrarCurso.setBackground(new java.awt.Color(255, 255, 255));
        JbCadastrarCurso.setForeground(new java.awt.Color(0, 0, 0));
        JbCadastrarCurso.setText("CADASTRAR");
        JbCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarCursoActionPerformed(evt);
            }
        });

        JbConsultarCurso.setBackground(new java.awt.Color(255, 255, 255));
        JbConsultarCurso.setForeground(new java.awt.Color(0, 0, 0));
        JbConsultarCurso.setText("CONSULTAR");
        JbConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarCursoActionPerformed(evt);
            }
        });

        JbEditarCurso.setBackground(new java.awt.Color(255, 255, 255));
        JbEditarCurso.setForeground(new java.awt.Color(0, 0, 0));
        JbEditarCurso.setText("EDITAR");
        JbEditarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEditarCursoActionPerformed(evt);
            }
        });

        JbExcluirCurso.setBackground(new java.awt.Color(255, 255, 255));
        JbExcluirCurso.setForeground(new java.awt.Color(0, 0, 0));
        JbExcluirCurso.setText("EXCLUIR");
        JbExcluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirCursoActionPerformed(evt);
            }
        });

        JbCarregarCamposCurso.setBackground(new java.awt.Color(255, 255, 255));
        JbCarregarCamposCurso.setForeground(new java.awt.Color(0, 0, 0));
        JbCarregarCamposCurso.setText(" CARREGAR CAMPOS");
        JbCarregarCamposCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarCamposCursoActionPerformed(evt);
            }
        });

        JbTabelCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME DO CURSO", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JbTabelCurso);

        CbxStatusCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ATIVO", "INATIVO" }));

        JtfCodigoCurso.setEnabled(false);
        JtfCodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfCodigoCursoActionPerformed(evt);
            }
        });

        JtfNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbCadastrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JbConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(JtfCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbEditarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JbExcluirCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JbCarregarCamposCurso))
                            .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jLabel3)
                    .addContainerGap(811, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtfCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCadastrarCurso)
                    .addComponent(JbConsultarCurso)
                    .addComponent(JbEditarCurso)
                    .addComponent(JbExcluirCurso)
                    .addComponent(JbCarregarCamposCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(jLabel3)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarCursoActionPerformed
        // TODO add your handling code here:
        listarCursoView();
    }//GEN-LAST:event_JbConsultarCursoActionPerformed

    private void JbEditarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEditarCursoActionPerformed
        alterarCursoView();
        listarCursoView();
        limparCampos();
    }//GEN-LAST:event_JbEditarCursoActionPerformed

    private void JbExcluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirCursoActionPerformed
        // TODO add your handling code here:
        excluirCursoView();
        listarCursoView();
        limparCampos();
    }//GEN-LAST:event_JbExcluirCursoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JbCarregarCamposCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarCamposCursoActionPerformed
        carregarCampos();
        
    }//GEN-LAST:event_JbCarregarCamposCursoActionPerformed

    private void JbCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarCursoActionPerformed
        Curso objCurso = new Curso(WIDTH, title, title);
        objCurso.setNome_curso(JtfNomeCurso.getText());
        objCurso.setStatus_curso(CbxStatusCurso.getSelectedItem().toString());
    if (JtfNomeCurso.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
    } else{
        ControleCurso objControleCurso = new ControleCurso();
        objControleCurso.cadastrarCurso(objCurso);
        JOptionPane.showMessageDialog(null, "Curso Cadastrado com sucesso!");
    }
        limparCampos();
        listarCursoView();

    }//GEN-LAST:event_JbCadastrarCursoActionPerformed

    private void JtfCodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfCodigoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfCodigoCursoActionPerformed

    private void JtfNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxStatusCurso;
    private javax.swing.JButton JbCadastrarCurso;
    private javax.swing.JButton JbCarregarCamposCurso;
    private javax.swing.JButton JbConsultarCurso;
    private javax.swing.JButton JbEditarCurso;
    private javax.swing.JButton JbExcluirCurso;
    private javax.swing.JTable JbTabelCurso;
    private javax.swing.JTextField JtfCodigoCurso;
    private javax.swing.JTextField JtfNomeCurso;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void Iconifiable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void cadastrarCursoView() {                                                 
        Curso objCurso = new Curso(WIDTH, title, title);
        objCurso.setNome_curso(JtfNomeCurso.getText());
        objCurso.setStatus_curso(CbxStatusCurso.getSelectedItem().toString());
        
    if (JtfNomeCurso.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
    } else{
        ControleCurso objControleCurso = new ControleCurso();
        objControleCurso.cadastrarCurso(objCurso);
        JOptionPane.showMessageDialog(null, "Curso Cadastrado com sucesso!");
        }
    }
    
    private void listarCursoView() {
        try {
            ControleCurso objControleCurso = new ControleCurso();
        // usar a tabela p/ montarr o modelo da tabela curso
        DefaultTableModel model = (DefaultTableModel) JbTabelCurso.getModel();
        model.setNumRows(0);
        
        ArrayList<Curso> lista = objControleCurso.consultarCurso();
            /* não sabemos qnts linhas serão então crio uma estrutura de repetição lista.size tamanho da nossa lista;
            num ++ incremento vai de 1 em 1*/    
            for (int num = 0; num < lista.size(); num++) {
                // adicionar uma linha para cada informação
                model.addRow(new Object[] {
                    lista.get(num).getId_curso(),
                    lista.get(num).getNome_curso(),
                    lista.get(num).getStatus_curso(),
                });
            }
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Lista Curso View JfLogin" + erro);
        }
    }
    
    private void carregarCampos(){
        // variavel local
        int setar = JbTabelCurso.getSelectedRow();
        
        JtfCodigoCurso.setText(JbTabelCurso.getModel().getValueAt(setar, 0).toString());
        JtfNomeCurso.setText(JbTabelCurso.getModel().getValueAt(setar, 1).toString());
        CbxStatusCurso.setSelectedItem(JbTabelCurso.getModel().getValueAt(setar, 2).toString());
    }
    
    
    private void alterarCursoView(){
        if (JtfNomeCurso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios ");
        } else{
            int codCurso = Integer.parseInt(JtfCodigoCurso.getText());
            Curso objCurso = new Curso(codCurso, JtfNomeCurso.getText(), CbxStatusCurso.getSelectedItem().toString());
            
            ControleCurso objControleCurso = new ControleCurso();
            objControleCurso.alterarCurso(objCurso);
            JOptionPane.showMessageDialog(null, "Curso alterado com Sucesso!");
        }
    }
    
    private void excluirCursoView(){
        if (JtfCodigoCurso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor, selecione um curso para exlcuir");
        } else{
            int comfirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este curso?", "comfirmação", JOptionPane.YES_NO_OPTION);
            if (comfirmacao == JOptionPane.YES_NO_OPTION){
                try {
                    Curso objCurso = new Curso(WIDTH, title, title);
                    objCurso.setId_curso(Integer.parseInt(JtfCodigoCurso.getText()));
                    //Instricionar o controlador e chamar o metodo para exclusão
                    ControleCurso objControleCurso = new ControleCurso();
                    objControleCurso.excluirCurso(objCurso);
                    
                    JOptionPane.showMessageDialog(null, "Curso excluido com sucesso!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro: ID ou código do curso inválido, verifique os dados");
                }
            }
        }
    }
    
    private void limparCampos(){
        JtfCodigoCurso.setText("");
        JtfNomeCurso.setText("");
        CbxStatusCurso.setSelectedIndex(0);
        // Focar e um campo especifico
        JtfNomeCurso.requestFocus();
    }
}
