package View;

import CONTROL.ControleAluno;
import CONTROL.ControleLivro;
import MODEL.Aluno;
import MODEL.Curso;
import MODEL.Livro;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Raquel
 */
public class JifLivros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JfAluno
     */
    
    private int idLivroSelecionado = 0;
    public JifLivros() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JbCarregarLivro = new javax.swing.JButton();
        JbCadastrarLivro = new javax.swing.JButton();
        JbConsultarLivro = new javax.swing.JButton();
        JbEditarLivro = new javax.swing.JButton();
        JbExcluirLivro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAluno = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtfAnoPublicacaoBiblioteca = new javax.swing.JFormattedTextField();
        JtfautorBiblioteca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JtftituloBiblioteca = new javax.swing.JTextField();
        JtfGeneroBiblioteca = new javax.swing.JTextField();
        JtfisbnBiblioteca = new javax.swing.JTextField();
        JtfEditoraBiblioteca = new javax.swing.JTextField();
        JtfIdiomaBiblioteca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JtfQuantidadeBiblioteca = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Formulário biblioteca");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editora");

        JbCarregarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbCarregarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbCarregarLivro.setText("CARREGAR CAMPOS");
        JbCarregarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarLivroActionPerformed(evt);
            }
        });

        JbCadastrarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbCadastrarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbCadastrarLivro.setText("CADASTRAR");
        JbCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarLivroActionPerformed(evt);
            }
        });

        JbConsultarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbConsultarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbConsultarLivro.setText("CONSULTAR");
        JbConsultarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarLivroActionPerformed(evt);
            }
        });

        JbEditarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbEditarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbEditarLivro.setText("EDITAR");
        JbEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEditarLivroActionPerformed(evt);
            }
        });

        JbExcluirLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbExcluirLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbExcluirLivro.setText("EXCLUIR");
        JbExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirLivroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Título");

        JTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ISBN", "TÍTULO", "AUTOR", "EDITORA", "ANO", "GENERO", "IDIOMA", "QTD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableAluno);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Autor");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ano de Publicação");

        JtfAnoPublicacaoBiblioteca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ISBN");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gênero");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Idioma");

        JtfGeneroBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfGeneroBibliotecaActionPerformed(evt);
            }
        });

        JtfEditoraBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfEditoraBibliotecaActionPerformed(evt);
            }
        });

        JtfIdiomaBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfIdiomaBibliotecaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quantidade");

        JtfQuantidadeBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfQuantidadeBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(JtfEditoraBiblioteca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(JtfisbnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(JtfAnoPublicacaoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(JtftituloBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JtfautorBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbConsultarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbEditarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfGeneroBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtfIdiomaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtfQuantidadeBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbExcluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbCarregarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JtftituloBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtfisbnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(JtfautorBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtfAnoPublicacaoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JtfEditoraBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfGeneroBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(JtfIdiomaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(JtfQuantidadeBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JbCadastrarLivro)
                            .addComponent(JbConsultarLivro)
                            .addComponent(JbEditarLivro)
                            .addComponent(JbExcluirLivro)
                            .addComponent(JbCarregarLivro))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCarregarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarLivroActionPerformed
        carregarCampos();
       
    }//GEN-LAST:event_JbCarregarLivroActionPerformed

    private void JbCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarLivroActionPerformed
        cadastrarLivroview();
        limparCampos();
        
    }//GEN-LAST:event_JbCadastrarLivroActionPerformed

    private void JbConsultarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarLivroActionPerformed
        listarLivroView();
    }//GEN-LAST:event_JbConsultarLivroActionPerformed

    private void JbEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEditarLivroActionPerformed
       alterarLivroView();
        listarLivroView();
        limparCampos();
       
    }//GEN-LAST:event_JbEditarLivroActionPerformed

    private void JbExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirLivroActionPerformed
          excluirLivroView();
        limparCampos();
        
    }//GEN-LAST:event_JbExcluirLivroActionPerformed

    private void JtfEditoraBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfEditoraBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfEditoraBibliotecaActionPerformed

    private void JtfGeneroBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfGeneroBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfGeneroBibliotecaActionPerformed

    private void JtfIdiomaBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfIdiomaBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfIdiomaBibliotecaActionPerformed

    private void JtfQuantidadeBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfQuantidadeBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfQuantidadeBibliotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableAluno;
    private javax.swing.JButton JbCadastrarLivro;
    private javax.swing.JButton JbCarregarLivro;
    private javax.swing.JButton JbConsultarLivro;
    private javax.swing.JButton JbEditarLivro;
    private javax.swing.JButton JbExcluirLivro;
    private javax.swing.JFormattedTextField JtfAnoPublicacaoBiblioteca;
    private javax.swing.JTextField JtfEditoraBiblioteca;
    private javax.swing.JTextField JtfGeneroBiblioteca;
    private javax.swing.JTextField JtfIdiomaBiblioteca;
    private javax.swing.JTextField JtfQuantidadeBiblioteca;
    private javax.swing.JTextField JtfautorBiblioteca;
    private javax.swing.JTextField JtfisbnBiblioteca;
    private javax.swing.JTextField JtftituloBiblioteca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables



     private void cadastrarLivroview() {
        if (!validarCampos()) return;
        try {
            Livro livro = new Livro();
            livro.setTitulo_livro(JtftituloBiblioteca.getText());
            livro.setAutor_livro(JtfautorBiblioteca.getText());
            livro.setEditora(JtfEditoraBiblioteca.getText());
            livro.setAno_publicacao(Integer.parseInt(JtfAnoPublicacaoBiblioteca.getText()));
            livro.setIsbn(Integer.parseInt(JtfisbnBiblioteca.getText()));
            livro.setGenero(JtfGeneroBiblioteca.getText());
            livro.setIdioma(JtfIdiomaBiblioteca.getText());
            livro.setQuantidade_estoque(Integer.parseInt(JtfQuantidadeBiblioteca.getText()));
            livro.setData_cadastro(new Date());

            new ControleLivro().cadastrarLivro(livro);
            JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
            listarLivroView();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage());
        }
    }

    private void listarLivroView() {
        try {
            DefaultTableModel model = (DefaultTableModel) JTableAluno.getModel();
            model.setRowCount(0);
            ArrayList<Livro> lista = new ControleLivro().consultarLivro();
            for (Livro l : lista) {
                model.addRow(new Object[]{
                    l.getId_livro(),       // 0 (oculto)
                    l.getIsbn(),           // 1
                    l.getTitulo_livro(),   // 2
                    l.getAutor_livro(),    // 3
                    l.getEditora(),        // 4
                    l.getAno_publicacao(), // 5
                    l.getGenero(),         // 6
                    l.getIdioma(),         // 7
                    l.getQuantidade_estoque() // 8
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar: " + e.getMessage());
        }
    }

    private void carregarCampos() {
        int linha = JTableAluno.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um livro na tabela!");
            return;
        }
        idLivroSelecionado = (int) JTableAluno.getValueAt(linha, 0);
        JtfisbnBiblioteca.setText(JTableAluno.getValueAt(linha, 1).toString());
        JtftituloBiblioteca.setText(JTableAluno.getValueAt(linha, 2).toString());
        JtfautorBiblioteca.setText(JTableAluno.getValueAt(linha, 3).toString());
        JtfEditoraBiblioteca.setText(JTableAluno.getValueAt(linha, 4).toString());
        JtfAnoPublicacaoBiblioteca.setText(JTableAluno.getValueAt(linha, 5).toString());
        JtfGeneroBiblioteca.setText(JTableAluno.getValueAt(linha, 6).toString());
        JtfIdiomaBiblioteca.setText(JTableAluno.getValueAt(linha, 7).toString());
        JtfQuantidadeBiblioteca.setText(JTableAluno.getValueAt(linha, 8).toString());
    }

    private void alterarLivroView() {
        if (idLivroSelecionado == 0) {
            JOptionPane.showMessageDialog(this, "Carregue um livro primeiro!");
            return;
        }
        if (!validarCampos()) return;
        try {
            Livro livro = new Livro();
            livro.setId_livro(idLivroSelecionado);
            livro.setIsbn(Integer.parseInt(JtfisbnBiblioteca.getText()));
            livro.setTitulo_livro(JtftituloBiblioteca.getText());
            livro.setAutor_livro(JtfautorBiblioteca.getText());
            livro.setEditora(JtfEditoraBiblioteca.getText());
            livro.setAno_publicacao(Integer.parseInt(JtfAnoPublicacaoBiblioteca.getText()));
            livro.setGenero(JtfGeneroBiblioteca.getText());
            livro.setIdioma(JtfIdiomaBiblioteca.getText());
            livro.setQuantidade_estoque(Integer.parseInt(JtfQuantidadeBiblioteca.getText()));

            new ControleLivro().alterarLivro(livro);
            JOptionPane.showMessageDialog(this, "Livro atualizado com sucesso!");
            listarLivroView();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
        }
    }

    private void excluirLivroView() {
        if (idLivroSelecionado == 0) {
            JOptionPane.showMessageDialog(this, "Carregue um livro primeiro!");
            return;
        }
        int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Excluir", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            new ControleLivro().excluirLivro(idLivroSelecionado);
            JOptionPane.showMessageDialog(this, "Livro excluído!");
            listarLivroView();
            limparCampos();
        }
    }

    private void limparCampos() {
        idLivroSelecionado = 0;
        JtfisbnBiblioteca.setText("");
        JtftituloBiblioteca.setText("");
        JtfautorBiblioteca.setText("");
        JtfEditoraBiblioteca.setText("");
        JtfAnoPublicacaoBiblioteca.setText("");
        JtfGeneroBiblioteca.setText("");
        JtfIdiomaBiblioteca.setText("");
        JtfQuantidadeBiblioteca.setText("");
        JtfisbnBiblioteca.requestFocus();
    }

    private boolean validarCampos() {
        if (JtftituloBiblioteca.getText().isEmpty() ||
            JtfautorBiblioteca.getText().isEmpty() ||
            JtfEditoraBiblioteca.getText().isEmpty() ||
            JtfAnoPublicacaoBiblioteca.getText().isEmpty() ||
            JtfisbnBiblioteca.getText().isEmpty() ||
            JtfGeneroBiblioteca.getText().isEmpty() ||
            JtfIdiomaBiblioteca.getText().isEmpty() ||
            JtfQuantidadeBiblioteca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!");
            return false;
        }
        try {
            Integer.parseInt(JtfisbnBiblioteca.getText());
            Integer.parseInt(JtfAnoPublicacaoBiblioteca.getText());
            Integer.parseInt(JtfQuantidadeBiblioteca.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ISBN, Ano e Quantidade devem ser números!");
            return false;
        }
        return true;
    }
}